# Generated by Django 2.1.2 on 2018-10-16 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20181016_2303'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['-name']},
        ),
    ]
