# Generated by Django 2.1.2 on 2018-10-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('answer', models.TextField(default='')),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
