# Generated by Django 2.1.2 on 2018-10-19 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0002_auto_20181018_0358'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('question', models.ImageField(height_field='300', upload_to='static', width_field='300')),
                ('text', models.TextField(blank=True, max_length=100)),
                ('question_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='levels.Answer')),
            ],
        ),
    ]
