# Generated by Django 2.1.2 on 2018-10-19 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0003_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='index',
        ),
    ]
