# Generated by Django 2.1.2 on 2018-10-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0004_remove_question_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.ImageField(upload_to='static'),
        ),
    ]
