# Generated by Django 2.1.2 on 2018-10-19 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0006_auto_20181019_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question',
            new_name='question_image',
        ),
    ]
