# Generated by Django 2.1.2 on 2018-10-19 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levels', '0011_auto_20181019_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_image',
            field=models.ImageField(upload_to='levels/media'),
        ),
    ]
